name: flare
version: 0.3.1
author: George Moschovitis <george.moschovitis@gmail.com>
description: Flare is a set of Barback transformers that collectively implement a versatile static-site generation system.
homepage: https://github.com/gmosx/dart-flare
dependencies:
  args: ">=0.12.0+1 <0.13.0"
  barback: ">=0.15.0 <0.16.0"
  intl: ">=0.8.10+4 <0.9.0"
  markdown: ">=0.7.0 <0.8.0"
  mustache: ">=0.1.8 <0.2.0"
  path: ">=1.2.2 <2.0.0"
  quiver: ">=0.18.2 <0.19.0"
  utf: ">=0.9.0+1 <0.10.0"
  uuid: ">=0.3.2 <0.4.0"
  yaml: ">=1.1.1 <2.0.0"
dev_dependencies:
  unittest: any
